# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(460, 428)
        self.btnJugar = QPushButton(Form)
        self.btnJugar.setObjectName(u"btnJugar")
        self.btnJugar.setGeometry(QRect(150, 400, 161, 21))
        self.btnJugar.setCheckable(False)
        self.Jugador1 = QGroupBox(Form)
        self.Jugador1.setObjectName(u"Jugador1")
        self.Jugador1.setGeometry(QRect(10, 10, 181, 351))
        self.seleccion1 = QComboBox(self.Jugador1)
        self.seleccion1.addItem("")
        self.seleccion1.addItem("")
        self.seleccion1.addItem("")
        self.seleccion1.setObjectName(u"seleccion1")
        self.seleccion1.setGeometry(QRect(10, 250, 161, 22))
        self.imgnUser1 = QLabel(self.Jugador1)
        self.imgnUser1.setObjectName(u"imgnUser1")
        self.imgnUser1.setGeometry(QRect(10, 90, 161, 151))
        self.imgnUser1.setScaledContents(True)
        self.label1 = QLabel(self.Jugador1)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 40, 47, 13))
        self.label2 = QLabel(self.Jugador1)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(70, 40, 47, 13))
        self.label3 = QLabel(self.Jugador1)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(130, 40, 47, 13))
        self.RAganado = QLabel(self.Jugador1)
        self.RAganado.setObjectName(u"RAganado")
        self.RAganado.setGeometry(QRect(10, 60, 47, 13))
        self.RAganado.setAlignment(Qt.AlignCenter)
        self.RAperdido = QLabel(self.Jugador1)
        self.RAperdido.setObjectName(u"RAperdido")
        self.RAperdido.setGeometry(QRect(70, 60, 47, 13))
        self.RAperdido.setAlignment(Qt.AlignCenter)
        self.RAempate = QLabel(self.Jugador1)
        self.RAempate.setObjectName(u"RAempate")
        self.RAempate.setGeometry(QRect(130, 60, 47, 13))
        self.RAempate.setAlignment(Qt.AlignCenter)
        self.RGperdido = QLabel(self.Jugador1)
        self.RGperdido.setObjectName(u"RGperdido")
        self.RGperdido.setGeometry(QRect(70, 330, 47, 13))
        self.RGperdido.setAlignment(Qt.AlignCenter)
        self.label2_3 = QLabel(self.Jugador1)
        self.label2_3.setObjectName(u"label2_3")
        self.label2_3.setGeometry(QRect(70, 310, 47, 13))
        self.RGempate = QLabel(self.Jugador1)
        self.RGempate.setObjectName(u"RGempate")
        self.RGempate.setGeometry(QRect(130, 330, 47, 13))
        self.RGempate.setAlignment(Qt.AlignCenter)
        self.label3_3 = QLabel(self.Jugador1)
        self.label3_3.setObjectName(u"label3_3")
        self.label3_3.setGeometry(QRect(130, 310, 47, 13))
        self.RGganado = QLabel(self.Jugador1)
        self.RGganado.setObjectName(u"RGganado")
        self.RGganado.setGeometry(QRect(10, 330, 47, 13))
        self.RGganado.setAlignment(Qt.AlignCenter)
        self.label1_3 = QLabel(self.Jugador1)
        self.label1_3.setObjectName(u"label1_3")
        self.label1_3.setGeometry(QRect(10, 310, 47, 13))
        self.label = QLabel(self.Jugador1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 280, 161, 16))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.Jugador1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 161, 16))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.Jugador2 = QGroupBox(Form)
        self.Jugador2.setObjectName(u"Jugador2")
        self.Jugador2.setGeometry(QRect(270, 10, 181, 351))
        self.imgnUser2 = QLabel(self.Jugador2)
        self.imgnUser2.setObjectName(u"imgnUser2")
        self.imgnUser2.setGeometry(QRect(10, 90, 161, 151))
        self.imgnUser2.setScaledContents(True)
        self.seleccion2 = QComboBox(self.Jugador2)
        self.seleccion2.addItem("")
        self.seleccion2.addItem("")
        self.seleccion2.addItem("")
        self.seleccion2.setObjectName(u"seleccion2")
        self.seleccion2.setGeometry(QRect(10, 250, 161, 22))
        self.label1_2 = QLabel(self.Jugador2)
        self.label1_2.setObjectName(u"label1_2")
        self.label1_2.setGeometry(QRect(10, 40, 47, 13))
        self.label3_2 = QLabel(self.Jugador2)
        self.label3_2.setObjectName(u"label3_2")
        self.label3_2.setGeometry(QRect(130, 40, 47, 13))
        self.label2_2 = QLabel(self.Jugador2)
        self.label2_2.setObjectName(u"label2_2")
        self.label2_2.setGeometry(QRect(70, 40, 47, 13))
        self.RAempate2 = QLabel(self.Jugador2)
        self.RAempate2.setObjectName(u"RAempate2")
        self.RAempate2.setGeometry(QRect(130, 60, 47, 13))
        self.RAempate2.setAlignment(Qt.AlignCenter)
        self.RAganado2 = QLabel(self.Jugador2)
        self.RAganado2.setObjectName(u"RAganado2")
        self.RAganado2.setGeometry(QRect(10, 60, 47, 13))
        self.RAganado2.setAlignment(Qt.AlignCenter)
        self.RAperdido2 = QLabel(self.Jugador2)
        self.RAperdido2.setObjectName(u"RAperdido2")
        self.RAperdido2.setGeometry(QRect(70, 60, 47, 13))
        self.RAperdido2.setAlignment(Qt.AlignCenter)
        self.RGempate2 = QLabel(self.Jugador2)
        self.RGempate2.setObjectName(u"RGempate2")
        self.RGempate2.setGeometry(QRect(130, 330, 47, 13))
        self.RGempate2.setAlignment(Qt.AlignCenter)
        self.RGperdido2 = QLabel(self.Jugador2)
        self.RGperdido2.setObjectName(u"RGperdido2")
        self.RGperdido2.setGeometry(QRect(70, 330, 47, 13))
        self.RGperdido2.setAlignment(Qt.AlignCenter)
        self.label3_4 = QLabel(self.Jugador2)
        self.label3_4.setObjectName(u"label3_4")
        self.label3_4.setGeometry(QRect(130, 310, 47, 13))
        self.RGganado2 = QLabel(self.Jugador2)
        self.RGganado2.setObjectName(u"RGganado2")
        self.RGganado2.setGeometry(QRect(10, 330, 47, 13))
        self.RGganado2.setAlignment(Qt.AlignCenter)
        self.label1_4 = QLabel(self.Jugador2)
        self.label1_4.setObjectName(u"label1_4")
        self.label1_4.setGeometry(QRect(10, 310, 47, 13))
        self.label2_4 = QLabel(self.Jugador2)
        self.label2_4.setObjectName(u"label2_4")
        self.label2_4.setGeometry(QRect(70, 310, 47, 13))
        self.label_2 = QLabel(self.Jugador2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 280, 161, 16))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.Jugador2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 161, 16))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.msjJuego = QLabel(Form)
        self.msjJuego.setObjectName(u"msjJuego")
        self.msjJuego.setGeometry(QRect(176, 370, 111, 20))
        self.msjJuego.setAlignment(Qt.AlignCenter)
        self.btnSalir = QPushButton(Form)
        self.btnSalir.setObjectName(u"btnSalir")
        self.btnSalir.setGeometry(QRect(360, 400, 80, 21))
        self.btnContinuar = QPushButton(Form)
        self.btnContinuar.setObjectName(u"btnContinuar")
        self.btnContinuar.setGeometry(QRect(20, 400, 80, 21))
        self.MsjSistema1 = QLabel(Form)
        self.MsjSistema1.setObjectName(u"MsjSistema1")
        self.MsjSistema1.setGeometry(QRect(20, 370, 141, 20))
        self.MsjSistema1.setTextFormat(Qt.MarkdownText)
        self.MsjSistema1.setAlignment(Qt.AlignCenter)
        self.MsjSistema2 = QLabel(Form)
        self.MsjSistema2.setObjectName(u"MsjSistema2")
        self.MsjSistema2.setGeometry(QRect(300, 370, 141, 20))
        self.MsjSistema2.setTextFormat(Qt.MarkdownText)
        self.MsjSistema2.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"EQUIPO", None))
        self.btnJugar.setText(QCoreApplication.translate("Form", u"Jugar", None))
        self.Jugador1.setTitle(QCoreApplication.translate("Form", u"JUGADOR 1", None))
        self.seleccion1.setItemText(0, QCoreApplication.translate("Form", u"Piedra", None))
        self.seleccion1.setItemText(1, QCoreApplication.translate("Form", u"Papel", None))
        self.seleccion1.setItemText(2, QCoreApplication.translate("Form", u"Tijera", None))

        self.imgnUser1.setText("")
        self.label1.setText(QCoreApplication.translate("Form", u"Ganado", None))
        self.label2.setText(QCoreApplication.translate("Form", u"Perdido", None))
        self.label3.setText(QCoreApplication.translate("Form", u"Empate", None))
        self.RAganado.setText("")
        self.RAperdido.setText("")
        self.RAempate.setText("")
        self.RGperdido.setText("")
        self.label2_3.setText(QCoreApplication.translate("Form", u"Perdido", None))
        self.RGempate.setText("")
        self.label3_3.setText(QCoreApplication.translate("Form", u"Empate", None))
        self.RGganado.setText("")
        self.label1_3.setText(QCoreApplication.translate("Form", u"Ganado", None))
        self.label.setText(QCoreApplication.translate("Form", u"RECORD GLOBAL", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"RECORD ACTUAL", None))
        self.Jugador2.setTitle(QCoreApplication.translate("Form", u"JUGADOR 2", None))
        self.imgnUser2.setText("")
        self.seleccion2.setItemText(0, QCoreApplication.translate("Form", u"Piedra", None))
        self.seleccion2.setItemText(1, QCoreApplication.translate("Form", u"Papel", None))
        self.seleccion2.setItemText(2, QCoreApplication.translate("Form", u"Tijera", None))

        self.seleccion2.setCurrentText(QCoreApplication.translate("Form", u"Piedra", None))
        self.label1_2.setText(QCoreApplication.translate("Form", u"Ganado", None))
        self.label3_2.setText(QCoreApplication.translate("Form", u"Empate", None))
        self.label2_2.setText(QCoreApplication.translate("Form", u"Perdido", None))
        self.RAempate2.setText("")
        self.RAganado2.setText("")
        self.RAperdido2.setText("")
        self.RGempate2.setText("")
        self.RGperdido2.setText("")
        self.label3_4.setText(QCoreApplication.translate("Form", u"Empate", None))
        self.RGganado2.setText("")
        self.label1_4.setText(QCoreApplication.translate("Form", u"Ganado", None))
        self.label2_4.setText(QCoreApplication.translate("Form", u"Perdido", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"RECORD GLOBAL", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"RECORD ACTUAL", None))
        self.msjJuego.setText("")
        self.btnSalir.setText(QCoreApplication.translate("Form", u"Salir", None))
        self.btnContinuar.setText(QCoreApplication.translate("Form", u"Continuar", None))
        self.MsjSistema1.setText("")
        self.MsjSistema2.setText("")
    # retranslateUi

